### ISSUE TITLE
Password Length Warning (Javascript)

### ISSUE THREAD

**Issue by aakatz3** [MHSCSClub/MHSAlumDB#35]
Warn the user with a tooltip, and gray out submit if passwords do not match or if they do not meet minimum requirements

**Comment by mb10456** [comment]
done

**Comment by aakatz3** [comment]
some asthetic issues still remain. Reassigning...

**Comment by aakatz3** [comment]
Code tested, and found not to work. Code was added to wrong page, and checks user name. It should not do that. Error messages are confusing. Reassigning.
